name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: pull-request-ci

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./unit-testing-using-dotnet-test

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    - uses: b3b00/coverlet-action@1.1.9
      with:
        testProject: 'PrimeService.Tests/PrimeService.Tests.csproj'
        output: 'lcov.info'
        outputFormat: 'lcov'
        excludes: '[program]*,[test]test.*'
        threshold: 90``
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
