name: push-images-repository

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'select-environment'
        type: environment
        required: true
        
jobs:

  build-push-images:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest